"""
AI Factory Pipeline v5.6 — App Logo & Design Asset Generator

Generates logos, splash screens, and icon sets for apps using the
free image generation chain (Pollinations → HuggingFace → Together).

Usage in pipeline (S2 Blueprint):
    from factory.design.logo_gen import generate_brand_assets
    assets = await generate_brand_assets(state, blueprint_data)
    # assets["logo_bytes"], assets["splash_bytes"], assets["logo_path"]

Spec Authority: v5.6 §4.3.1 (Design Asset Generation)
"""

from __future__ import annotations

import logging
import os
from typing import Optional

from factory.integrations.image_gen import (
    generate_image,
    build_logo_prompt,
    build_splash_prompt,
)

logger = logging.getLogger("factory.design.logo_gen")


# ═══════════════════════════════════════════════════════════════════
# Main Entry Point
# ═══════════════════════════════════════════════════════════════════


async def generate_brand_assets(
    state,
    blueprint_data: dict,
) -> dict:
    """Generate logo + splash screen for the app.

    Args:
        state: PipelineState (for project_id, idea_name, s0_output)
        blueprint_data: S2 blueprint dict (color_palette, app_name, etc.)

    Returns:
        Dict with keys:
            logo_bytes: PNG bytes or None
            splash_bytes: PNG bytes or None
            logo_path: local file path if saved, else None
            splash_path: local file path if saved, else None
            logo_prompt: the prompt used
    """
    project_id = state.project_id
    app_name = (
        blueprint_data.get("app_name")
        or state.idea_name
        or (state.s0_output or {}).get("app_name")
        or "App"
    )
    description = (state.s0_output or {}).get("app_description", "")
    colors = blueprint_data.get("color_palette", {})
    primary = colors.get("primary", "#6366f1")
    secondary = colors.get("secondary", "#8b5cf6")

    results: dict = {
        "logo_bytes": None,
        "splash_bytes": None,
        "logo_path": None,
        "splash_path": None,
        "logo_prompt": "",
    }

    # ── Logo ──
    logo_prompt = build_logo_prompt(app_name, description, primary)
    results["logo_prompt"] = logo_prompt
    logger.info(f"[{project_id}] Generating logo for '{app_name}'")

    logo_bytes = await generate_image(
        prompt=logo_prompt,
        width=1024,
        height=1024,
        style="flat app icon",
    )

    if logo_bytes:
        results["logo_bytes"] = logo_bytes
        path = _save_asset(logo_bytes, state, "logo.png")
        results["logo_path"] = path
        logger.info(f"[{project_id}] Logo generated ({len(logo_bytes)} bytes)")
    else:
        logger.warning(f"[{project_id}] Logo generation failed — all providers exhausted")

    # ── Splash Screen ──
    splash_prompt = build_splash_prompt(app_name, description, primary, secondary)
    logger.info(f"[{project_id}] Generating splash screen")

    splash_bytes = await generate_image(
        prompt=splash_prompt,
        width=1080,
        height=1920,
        style="mobile app splash screen",
    )

    if splash_bytes:
        results["splash_bytes"] = splash_bytes
        path = _save_asset(splash_bytes, state, "splash.png")
        results["splash_path"] = path
        logger.info(f"[{project_id}] Splash generated ({len(splash_bytes)} bytes)")
    else:
        logger.warning(f"[{project_id}] Splash generation failed")

    return results


# ═══════════════════════════════════════════════════════════════════
# Telegram Delivery Helper
# ═══════════════════════════════════════════════════════════════════


async def send_brand_assets_to_telegram(
    operator_id: str,
    assets: dict,
    app_name: str,
) -> None:
    """Send generated logo and splash screen to the operator via Telegram.

    Silently skips assets that are None.
    """
    from factory.telegram.notifications import send_telegram_message

    if not assets.get("logo_bytes") and not assets.get("splash_bytes"):
        await send_telegram_message(
            operator_id,
            f"Design assets for {app_name} could not be generated. "
            "The pipeline will continue with placeholder assets."
        )
        return

    try:
        from factory.app import _get_bot_app
        bot_app = _get_bot_app()
        bot = bot_app.bot if bot_app else None
    except Exception:
        bot = None

    if not bot:
        logger.warning("Bot instance unavailable — skipping asset Telegram delivery")
        return

    import io
    caption_logo = (
        f"🎨 *{app_name}* — App Icon\n"
        "Generated by the AI design pipeline. You can request changes later."
    )
    caption_splash = f"🖼 *{app_name}* — Splash Screen"

    if assets.get("logo_bytes"):
        try:
            await bot.send_photo(
                chat_id=int(operator_id),
                photo=io.BytesIO(assets["logo_bytes"]),
                caption=caption_logo,
                parse_mode="Markdown",
            )
        except Exception as e:
            logger.warning(f"Failed to send logo to Telegram: {e}")

    if assets.get("splash_bytes"):
        try:
            await bot.send_photo(
                chat_id=int(operator_id),
                photo=io.BytesIO(assets["splash_bytes"]),
                caption=caption_splash,
                parse_mode="Markdown",
            )
        except Exception as e:
            logger.warning(f"Failed to send splash to Telegram: {e}")


# ═══════════════════════════════════════════════════════════════════
# Internal: Save to workspace
# ═══════════════════════════════════════════════════════════════════


def _save_asset(data: bytes, state, filename: str) -> Optional[str]:
    """Save asset bytes to the project workspace. Returns path or None."""
    try:
        from factory.core.execution import _get_project_workspace
        workspace = _get_project_workspace(
            state.project_id,
            app_name=(state.s0_output or {}).get("app_name") or state.idea_name,
        )
        assets_dir = os.path.join(workspace, "assets", "branding")
        os.makedirs(assets_dir, exist_ok=True)
        path = os.path.join(assets_dir, filename)
        with open(path, "wb") as f:
            f.write(data)
        return path
    except Exception as e:
        logger.warning(f"Failed to save asset {filename}: {e}")
        return None
