"""
AI Factory Pipeline v5.8 — App Logo & Design Asset Generator

Generates logos, splash screens, and icon sets for apps using the
free image generation chain (Pollinations → HuggingFace → Together).

Usage in pipeline (S2 Blueprint):
    from factory.design.logo_gen import generate_brand_assets
    assets = await generate_brand_assets(state, blueprint_data)
    # assets["logo_bytes"], assets["splash_bytes"], assets["logo_path"]

Spec Authority: v5.8 §4.3.1 (Design Asset Generation)
"""

from __future__ import annotations

import logging
import os
from typing import Optional

from factory.integrations.image_gen import (
    generate_image,
    build_logo_prompt,
    build_splash_prompt,
)

logger = logging.getLogger("factory.design.logo_gen")


# ═══════════════════════════════════════════════════════════════════
# Main Entry Point
# ═══════════════════════════════════════════════════════════════════


async def generate_brand_assets(
    state,
    blueprint_data: dict,
) -> dict:
    """Generate logo + splash screen for the app.

    Args:
        state: PipelineState (for project_id, idea_name, s0_output)
        blueprint_data: S2 blueprint dict (color_palette, app_name, etc.)

    Returns:
        Dict with keys:
            logo_bytes: PNG bytes or None
            splash_bytes: PNG bytes or None
            logo_path: local file path if saved, else None
            splash_path: local file path if saved, else None
            logo_prompt: the prompt used
    """
    project_id = state.project_id
    app_name = (
        blueprint_data.get("app_name")
        or state.idea_name
        or (state.s0_output or {}).get("app_name")
        or "App"
    )
    description = (state.s0_output or {}).get("app_description", "")
    colors = blueprint_data.get("color_palette", {})
    primary = colors.get("primary", "#6366f1")
    secondary = colors.get("secondary", "#8b5cf6")

    results: dict = {
        "logo_bytes": None,
        "splash_bytes": None,
        "logo_path": None,
        "splash_path": None,
        "logo_prompt": "",
    }

    # ── Logo ──
    logo_prompt = build_logo_prompt(app_name, description, primary)
    results["logo_prompt"] = logo_prompt
    logger.info(f"[{project_id}] Generating logo for '{app_name}'")

    logo_bytes = await generate_image(
        prompt=logo_prompt,
        width=1024,
        height=1024,
        style="flat app icon",
    )

    if logo_bytes:
        results["logo_bytes"] = logo_bytes
        path = _save_asset(logo_bytes, state, "logo.png")
        results["logo_path"] = path
        logger.info(f"[{project_id}] Logo generated ({len(logo_bytes)} bytes)")
    else:
        logger.warning(f"[{project_id}] Logo generation failed — all providers exhausted")

    # ── Splash Screen ──
    splash_prompt = build_splash_prompt(app_name, description, primary, secondary)
    logger.info(f"[{project_id}] Generating splash screen")

    splash_bytes = await generate_image(
        prompt=splash_prompt,
        width=1080,
        height=1920,
        style="mobile app splash screen",
    )

    if splash_bytes:
        results["splash_bytes"] = splash_bytes
        path = _save_asset(splash_bytes, state, "splash.png")
        results["splash_path"] = path
        logger.info(f"[{project_id}] Splash generated ({len(splash_bytes)} bytes)")
    else:
        logger.warning(f"[{project_id}] Splash generation failed")

    return results


# ═══════════════════════════════════════════════════════════════════
# Telegram Delivery Helper
# ═══════════════════════════════════════════════════════════════════


async def send_brand_assets_to_telegram(
    operator_id: str,
    assets: dict,
    app_name: str,
) -> None:
    """Send generated logo and splash screen to the operator via Telegram.

    Silently skips assets that are None.
    """
    from factory.telegram.notifications import send_telegram_message

    if not assets.get("logo_bytes") and not assets.get("splash_bytes"):
        await send_telegram_message(
            operator_id,
            f"Design assets for {app_name} could not be generated. "
            "The pipeline will continue with placeholder assets."
        )
        return

    try:
        from factory.app import _get_bot_app
        bot_app = _get_bot_app()
        bot = bot_app.bot if bot_app else None
    except Exception:
        bot = None

    if not bot:
        logger.warning("Bot instance unavailable — skipping asset Telegram delivery")
        return

    import io
    caption_logo = (
        f"🎨 *{app_name}* — App Icon\n"
        "Generated by the AI design pipeline. You can request changes later."
    )
    caption_splash = f"🖼 *{app_name}* — Splash Screen"

    if assets.get("logo_bytes"):
        try:
            await bot.send_photo(
                chat_id=int(operator_id),
                photo=io.BytesIO(assets["logo_bytes"]),
                caption=caption_logo,
                parse_mode="Markdown",
            )
        except Exception as e:
            logger.warning(f"Failed to send logo to Telegram: {e}")

    if assets.get("splash_bytes"):
        try:
            await bot.send_photo(
                chat_id=int(operator_id),
                photo=io.BytesIO(assets["splash_bytes"]),
                caption=caption_splash,
                parse_mode="Markdown",
            )
        except Exception as e:
            logger.warning(f"Failed to send splash to Telegram: {e}")


# ═══════════════════════════════════════════════════════════════════
# Internal: Save to workspace
# ═══════════════════════════════════════════════════════════════════


async def generate_logo_variants(
    app_name: str,
    description: str,
    count: int = 3,
    primary_color: str = "#6366f1",
) -> list[Optional[bytes]]:
    """Generate N logo variants **concurrently** with different styles/seeds.

    Spec: v5.8 §4.1 — S0 logo flow (3 variants for operator pick).
    v5.8.16 Phase 6: all variants generated in parallel so total wait time
    equals one generation (≈30-45 s) rather than 3× sequential (≈90-135 s).

    Returns:
        List of raw PNG bytes (None for any variant that failed).
    """
    import asyncio as _asyncio

    styles = [
        "modern flat icon design, geometric shapes, bold colors, clean minimal",
        "minimalist icon, monochrome palette, simple bold shapes, professional",
        "colorful gradient icon, rounded corners, friendly vibrant feel, vector art",
    ]

    async def _gen_one(i: int) -> Optional[bytes]:
        style = styles[i % len(styles)]
        prompt = (
            f"App icon for '{app_name}'. {description[:100]}. "
            f"Style: {style}. Dominant color {primary_color}. "
            f"No text, no letters, no numbers. Square format. "
            f"White or transparent background. High quality. App store ready."
        )
        # Stagger starts to avoid hitting the same provider rate-limit window
        await _asyncio.sleep(i * 3)
        for attempt in range(3):
            try:
                img = await generate_image(
                    prompt=prompt,
                    width=1024,
                    height=1024,
                    seed=42 + i * 1337 + attempt * 997,
                )
                if img:
                    return img
                # provider returned None without raising — try next seed
            except Exception as e:
                logger.warning(
                    f"Logo variant {i + 1} attempt {attempt + 1} failed: {e}"
                )
            if attempt < 2:
                await _asyncio.sleep(5 * (attempt + 1))  # 5 s, then 10 s back-off
        return None

    results = await _asyncio.gather(*[_gen_one(i) for i in range(count)])
    succeeded = sum(1 for b in results if b)
    logger.info(
        f"[logo_gen] Generated {succeeded}/{count} variants for '{app_name}'"
    )
    return list(results)


async def send_logo_variants_to_telegram(
    operator_id: str,
    variants: list[Optional[bytes]],
    app_name: str,
) -> int:
    """Send logo variant images to the operator via Telegram.

    v5.8.16 Phase 6: sends as a single media album (InputMediaPhoto) so all
    3 variants appear together in one gallery-style message, making the pick
    experience natural.  Falls back to individual photo sends if the bot
    version doesn't support send_media_group.

    Returns the number of successfully sent variants.
    """
    from factory.telegram.notifications import get_bot
    bot = get_bot()
    if not bot:
        logger.warning("Bot unavailable — cannot send logo variants")
        return 0

    import io as _io

    valid: list[tuple[int, bytes]] = [
        (i + 1, b) for i, b in enumerate(variants) if b
    ]
    if not valid:
        return 0

    # ── Attempt media album (best UX — all 3 in one message) ──
    try:
        from telegram import InputMediaPhoto

        media_group = []
        for idx, img_bytes in valid:
            caption = (
                f"🎨 Variant {idx} / {len(valid)}  •  {app_name}"
                if idx == valid[-1][0]
                else f"🎨 Variant {idx} / {len(valid)}"
            )
            media_group.append(
                InputMediaPhoto(
                    media=_io.BytesIO(img_bytes),
                    caption=caption,
                )
            )
        await bot.send_media_group(
            chat_id=int(operator_id),
            media=media_group,
        )
        logger.info(
            f"[logo_gen] Sent {len(valid)}-variant album to {operator_id}"
        )
        return len(valid)

    except Exception as album_err:
        logger.warning(
            f"[logo_gen] Media album failed ({album_err}), "
            "falling back to individual photos"
        )

    # ── Fallback: send individually ──
    sent = 0
    for idx, img_bytes in valid:
        try:
            await bot.send_photo(
                chat_id=int(operator_id),
                photo=_io.BytesIO(img_bytes),
                caption=f"🎨 Variant {idx} / {len(valid)}  •  {app_name}",
            )
            sent += 1
        except Exception as e:
            logger.warning(f"[logo_gen] Failed to send variant {idx}: {e}")

    return sent


def _save_asset(data: bytes, state, filename: str) -> Optional[str]:
    """Save asset bytes to the project workspace. Returns path or None."""
    try:
        from factory.core.execution import _get_project_workspace
        workspace = _get_project_workspace(
            state.project_id,
            app_name=(state.s0_output or {}).get("app_name") or state.idea_name,
        )
        assets_dir = os.path.join(workspace, "assets", "branding")
        os.makedirs(assets_dir, exist_ok=True)
        path = os.path.join(assets_dir, filename)
        with open(path, "wb") as f:
            f.write(data)
        return path
    except Exception as e:
        logger.warning(f"Failed to save asset {filename}: {e}")
        return None
